// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6I2NJrfC9c_1E0Krw6wE0S0Asa9St_1g',
    appId: '1:317455411891:android:0b056bf476c1a47f619ec6',
    messagingSenderId: '317455411891',
    projectId: 'echoalert-58e07',
    storageBucket: 'echoalert-58e07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-LXAjvtlt0OsOHEMnaaKbTIxkZvFDw08',
    appId: '1:317455411891:ios:a45770a8118c6a00619ec6',
    messagingSenderId: '317455411891',
    projectId: 'echoalert-58e07',
    storageBucket: 'echoalert-58e07.firebasestorage.app',
    iosBundleId: 'com.example.echoalert',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGhUYoCtP63DnsgAH4mPZLYLHHqcGbqk4',
    appId: '1:317455411891:web:5abbfdbea459e1cf619ec6',
    messagingSenderId: '317455411891',
    projectId: 'echoalert-58e07',
    authDomain: 'echoalert-58e07.firebaseapp.com',
    storageBucket: 'echoalert-58e07.firebasestorage.app',
    measurementId: 'G-923WKCH5MX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-LXAjvtlt0OsOHEMnaaKbTIxkZvFDw08',
    appId: '1:317455411891:ios:a45770a8118c6a00619ec6',
    messagingSenderId: '317455411891',
    projectId: 'echoalert-58e07',
    storageBucket: 'echoalert-58e07.firebasestorage.app',
    iosBundleId: 'com.example.echoalert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGhUYoCtP63DnsgAH4mPZLYLHHqcGbqk4',
    appId: '1:317455411891:web:55d5887f4cc957f5619ec6',
    messagingSenderId: '317455411891',
    projectId: 'echoalert-58e07',
    authDomain: 'echoalert-58e07.firebaseapp.com',
    storageBucket: 'echoalert-58e07.firebasestorage.app',
    measurementId: 'G-03GFP9L235',
  );

}